
class TypeKinds(object):
    # special unsupported type
    unsupported = 0

    # base types
    int = 0x01
    uint = 0x02
    char = 0x03
    uchar = 0x04
    float = 0x05
    bool = 0x06

    # modifiers
    const = 0x10
    packed = 0x11
    ptr = 0x12
    ref = 0x13
    rref = 0x14
    shared = 0x15
    volatile = 0x16
    restrict = 0x17
    array = 0x18

    # compound
    struct = 0x20
    cls = 0x21
    union = 0x22

    # other special types
    typedef = 0x30
    enum = 0x31
    function = 0x32

    # various kinds not present in C/C++ or not generated by GCC
    condition = 0x40
    string = 0x41
    set = 0x42
    subrange = 0x43
    memberptr = 0x44
    file = 0x45
    template_alias = 0x46
    

class InsnKinds(object):
    nocode = 0
    arm64 = 8
    arm = 4
    thumb = 2
